/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package flatcolorpicker;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import javax.swing.ImageIcon;

/*
 *  This Code Was Written By
 *     redb3n@gmail.com
 *        Reda Ben
 */
public class Maibn extends javax.swing.JFrame {

    /** Creates new form Maibn */
    public Maibn() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        c10 = new javax.swing.JLabel();
        c9 = new javax.swing.JLabel();
        c8 = new javax.swing.JLabel();
        c7 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        yellow = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        c32 = new javax.swing.JLabel();
        c33 = new javax.swing.JLabel();
        c34 = new javax.swing.JLabel();
        c36 = new javax.swing.JLabel();
        c38 = new javax.swing.JLabel();
        purple = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        c21 = new javax.swing.JLabel();
        c22 = new javax.swing.JLabel();
        c23 = new javax.swing.JLabel();
        c24 = new javax.swing.JLabel();
        c25 = new javax.swing.JLabel();
        c26 = new javax.swing.JLabel();
        c27 = new javax.swing.JLabel();
        c28 = new javax.swing.JLabel();
        c29 = new javax.swing.JLabel();
        red = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        c12 = new javax.swing.JLabel();
        c13 = new javax.swing.JLabel();
        c14 = new javax.swing.JLabel();
        c15 = new javax.swing.JLabel();
        c16 = new javax.swing.JLabel();
        c17 = new javax.swing.JLabel();
        c18 = new javax.swing.JLabel();
        c19 = new javax.swing.JLabel();
        c20 = new javax.swing.JLabel();
        blue = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        orange = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 4, 30, 30));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 4, 30, 30));

        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel4MouseDragged(evt);
            }
        });
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        main.setOpaque(false);
        main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c10.setBackground(new java.awt.Color(171, 183, 183));
        c10.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c10.setForeground(new java.awt.Color(255, 236, 219));
        c10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c10.setText("Other");
        c10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        main.add(c10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 140, 140));

        c9.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/other.png"))); // NOI18N
        c9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        main.add(c9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 140, 140));

        c8.setBackground(new java.awt.Color(1, 152, 117));
        c8.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c8.setForeground(new java.awt.Color(63, 195, 128));
        c8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c8.setText("Gray");
        c8.setToolTipText("");
        c8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c8.setOpaque(true);
        main.add(c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 140, 140));

        c7.setBackground(new java.awt.Color(210, 82, 127));
        c7.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c7.setForeground(new java.awt.Color(241, 169, 160));
        c7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c7.setText("Pink");
        c7.setToolTipText("");
        c7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c7.setOpaque(true);
        main.add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, 140));

        c6.setBackground(new java.awt.Color(171, 183, 183));
        c6.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c6.setForeground(new java.awt.Color(108, 122, 137));
        c6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c6.setText("Gray");
        c6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c6.setOpaque(true);
        main.add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 140, 140));

        c5.setBackground(new java.awt.Color(235, 151, 78));
        c5.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c5.setForeground(new java.awt.Color(249, 191, 59));
        c5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c5.setText("Orange");
        c5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c5.setOpaque(true);
        c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c5MouseClicked(evt);
            }
        });
        main.add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 140, 140));

        c4.setBackground(new java.awt.Color(247, 202, 24));
        c4.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c4.setForeground(new java.awt.Color(253, 227, 167));
        c4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c4.setText("Yellow");
        c4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c4.setOpaque(true);
        c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c4MouseClicked(evt);
            }
        });
        main.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 140));

        c3.setBackground(new java.awt.Color(142, 68, 173));
        c3.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c3.setForeground(new java.awt.Color(103, 65, 114));
        c3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c3.setText("Purple");
        c3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c3.setOpaque(true);
        c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c3MouseClicked(evt);
            }
        });
        main.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 140, 140));

        c2.setBackground(new java.awt.Color(214, 69, 65));
        c2.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c2.setForeground(new java.awt.Color(150, 40, 27));
        c2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c2.setText("Red");
        c2.setToolTipText("");
        c2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c2.setOpaque(true);
        c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c2MouseClicked(evt);
            }
        });
        main.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 140, 140));

        c1.setBackground(new java.awt.Color(82, 179, 217));
        c1.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c1.setForeground(new java.awt.Color(37, 116, 169));
        c1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c1.setText("Blue");
        c1.setToolTipText("");
        c1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c1.setOpaque(true);
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1MouseClicked(evt);
            }
        });
        main.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 140));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/rbg.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        main.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 310, 40));

        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 450, 480));

        yellow.setOpaque(false);
        yellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                yellowMouseEntered(evt);
            }
        });
        yellow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Secret Code", 1, 48)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Copied");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 190, 80));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 120, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 120, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 120, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 120, -1));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel4.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 120, -1));

        yellow.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 480, 110));

        jLabel48.setBackground(new java.awt.Color(0, 153, 153));
        jLabel48.setFont(new java.awt.Font("Secret Code", 1, 24)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Back");
        jLabel48.setToolTipText("");
        jLabel48.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel48.setOpaque(true);
        jLabel48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel48MouseClicked(evt);
            }
        });
        yellow.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 80, 40));

        c32.setBackground(new java.awt.Color(247, 202, 24));
        c32.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c32.setForeground(new java.awt.Color(253, 227, 167));
        c32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c32.setToolTipText("");
        c32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c32.setOpaque(true);
        c32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c32MouseClicked(evt);
            }
        });
        yellow.add(c32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, 140));

        c33.setBackground(new java.awt.Color(244, 208, 63));
        c33.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c33.setForeground(new java.awt.Color(249, 191, 59));
        c33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c33.setToolTipText("");
        c33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c33.setOpaque(true);
        c33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c33MouseClicked(evt);
            }
        });
        yellow.add(c33, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 140, 140));

        c34.setBackground(new java.awt.Color(255, 213, 108));
        c34.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c34.setForeground(new java.awt.Color(108, 122, 137));
        c34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c34.setToolTipText("");
        c34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c34.setOpaque(true);
        c34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c34MouseClicked(evt);
            }
        });
        yellow.add(c34, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 140, 140));

        c36.setBackground(new java.awt.Color(245, 215, 110));
        c36.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c36.setForeground(new java.awt.Color(150, 40, 27));
        c36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c36.setToolTipText("");
        c36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c36.setOpaque(true);
        c36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c36MouseClicked(evt);
            }
        });
        yellow.add(c36, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, 140));

        c38.setBackground(new java.awt.Color(255, 224, 87));
        c38.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c38.setForeground(new java.awt.Color(63, 195, 128));
        c38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c38.setToolTipText("");
        c38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c38.setOpaque(true);
        c38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c38MouseClicked(evt);
            }
        });
        yellow.add(c38, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 140, 140));

        getContentPane().add(yellow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 480, 500));

        purple.setOpaque(false);
        purple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                purpleMouseEntered(evt);
            }
        });
        purple.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Secret Code", 1, 48)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Copied");
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 190, 80));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 120, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 120, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 120, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel3.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 120, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel3.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 120, -1));

        purple.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 480, 110));

        jLabel47.setBackground(new java.awt.Color(0, 153, 153));
        jLabel47.setFont(new java.awt.Font("Secret Code", 1, 24)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Back");
        jLabel47.setToolTipText("");
        jLabel47.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel47.setOpaque(true);
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        purple.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 80, 40));

        c21.setBackground(new java.awt.Color(154, 18, 179));
        c21.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c21.setForeground(new java.awt.Color(63, 195, 128));
        c21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c21.setToolTipText("");
        c21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c21.setOpaque(true);
        c21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c21MouseClicked(evt);
            }
        });
        purple.add(c21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 140, 140));

        c22.setBackground(new java.awt.Color(142, 68, 173));
        c22.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c22.setForeground(new java.awt.Color(241, 169, 160));
        c22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c22.setToolTipText("");
        c22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c22.setOpaque(true);
        c22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c22MouseClicked(evt);
            }
        });
        purple.add(c22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, 140));

        c23.setBackground(new java.awt.Color(220, 198, 224));
        c23.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c23.setForeground(new java.awt.Color(253, 227, 167));
        c23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c23.setToolTipText("");
        c23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c23.setOpaque(true);
        c23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c23MouseClicked(evt);
            }
        });
        purple.add(c23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, 140));

        c24.setBackground(new java.awt.Color(102, 51, 153));
        c24.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c24.setForeground(new java.awt.Color(249, 191, 59));
        c24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c24.setToolTipText("");
        c24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c24.setOpaque(true);
        c24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c24MouseClicked(evt);
            }
        });
        purple.add(c24, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 140, 140));

        c25.setBackground(new java.awt.Color(103, 65, 114));
        c25.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c25.setForeground(new java.awt.Color(108, 122, 137));
        c25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c25.setToolTipText("");
        c25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c25.setOpaque(true);
        c25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c25MouseClicked(evt);
            }
        });
        purple.add(c25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 140, 140));

        c26.setBackground(new java.awt.Color(154, 18, 179));
        c26.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c26.setForeground(new java.awt.Color(103, 65, 114));
        c26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c26.setToolTipText("");
        c26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c26.setOpaque(true);
        c26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c26MouseClicked(evt);
            }
        });
        purple.add(c26, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 140, 140));

        c27.setBackground(new java.awt.Color(155, 89, 182));
        c27.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c27.setForeground(new java.awt.Color(150, 40, 27));
        c27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c27.setToolTipText("");
        c27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c27.setOpaque(true);
        c27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c27MouseClicked(evt);
            }
        });
        purple.add(c27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, 140));

        c28.setBackground(new java.awt.Color(145, 61, 136));
        c28.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c28.setForeground(new java.awt.Color(37, 116, 169));
        c28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c28.setToolTipText("");
        c28.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c28.setOpaque(true);
        c28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c28MouseClicked(evt);
            }
        });
        purple.add(c28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 140));

        c29.setBackground(new java.awt.Color(190, 144, 212));
        c29.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c29.setForeground(new java.awt.Color(63, 195, 128));
        c29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c29.setToolTipText("");
        c29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c29.setOpaque(true);
        c29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c29MouseClicked(evt);
            }
        });
        purple.add(c29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 140, 140));

        getContentPane().add(purple, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 480, 500));

        red.setOpaque(false);
        red.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                redMouseEntered(evt);
            }
        });
        red.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Secret Code", 1, 48)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Copied");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 190, 80));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 120, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 120, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 120, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 120, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 120, -1));

        red.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 480, 110));

        jLabel46.setBackground(new java.awt.Color(0, 153, 153));
        jLabel46.setFont(new java.awt.Font("Secret Code", 1, 24)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Back");
        jLabel46.setToolTipText("");
        jLabel46.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel46.setOpaque(true);
        jLabel46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel46MouseClicked(evt);
            }
        });
        red.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 80, 40));

        c12.setBackground(new java.awt.Color(207, 0, 15));
        c12.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c12.setForeground(new java.awt.Color(63, 195, 128));
        c12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c12.setToolTipText("");
        c12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c12.setOpaque(true);
        c12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c12MouseClicked(evt);
            }
        });
        red.add(c12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 140, 140));

        c13.setBackground(new java.awt.Color(239, 72, 54));
        c13.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c13.setForeground(new java.awt.Color(241, 169, 160));
        c13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c13.setToolTipText("");
        c13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c13.setOpaque(true);
        c13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c13MouseClicked(evt);
            }
        });
        red.add(c13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, 140));

        c14.setBackground(new java.awt.Color(242, 38, 19));
        c14.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c14.setForeground(new java.awt.Color(253, 227, 167));
        c14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c14.setToolTipText("");
        c14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c14.setOpaque(true);
        c14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c14MouseClicked(evt);
            }
        });
        red.add(c14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, 140));

        c15.setBackground(new java.awt.Color(217, 30, 24));
        c15.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c15.setForeground(new java.awt.Color(249, 191, 59));
        c15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c15.setToolTipText("");
        c15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c15.setOpaque(true);
        c15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c15MouseClicked(evt);
            }
        });
        red.add(c15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 140, 140));

        c16.setBackground(new java.awt.Color(150, 40, 27));
        c16.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c16.setForeground(new java.awt.Color(108, 122, 137));
        c16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c16.setToolTipText("");
        c16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c16.setOpaque(true);
        c16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c16MouseClicked(evt);
            }
        });
        red.add(c16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 140, 140));

        c17.setBackground(new java.awt.Color(214, 69, 65));
        c17.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c17.setForeground(new java.awt.Color(103, 65, 114));
        c17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c17.setToolTipText("");
        c17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c17.setOpaque(true);
        c17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c17MouseClicked(evt);
            }
        });
        red.add(c17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 140, 140));

        c18.setBackground(new java.awt.Color(239, 72, 54));
        c18.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c18.setForeground(new java.awt.Color(150, 40, 27));
        c18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c18.setToolTipText("");
        c18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c18.setOpaque(true);
        c18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c18MouseClicked(evt);
            }
        });
        red.add(c18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, 140));

        c19.setBackground(new java.awt.Color(210, 77, 87));
        c19.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c19.setForeground(new java.awt.Color(37, 116, 169));
        c19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c19.setToolTipText("");
        c19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c19.setOpaque(true);
        c19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c19MouseClicked(evt);
            }
        });
        red.add(c19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 140));

        c20.setBackground(new java.awt.Color(192, 57, 43));
        c20.setFont(new java.awt.Font("Secret Code", 1, 36)); // NOI18N
        c20.setForeground(new java.awt.Color(63, 195, 128));
        c20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c20.setToolTipText("");
        c20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c20.setOpaque(true);
        c20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c20MouseClicked(evt);
            }
        });
        red.add(c20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 140, 140));

        getContentPane().add(red, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 480, 500));

        blue.setOpaque(false);
        blue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                blueMouseEntered(evt);
            }
        });
        blue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Secret Code", 1, 48)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Copied");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 190, 80));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 120, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 120, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 120, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 120, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 120, -1));

        blue.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 480, 110));

        jLabel5.setBackground(new java.awt.Color(228, 241, 254));
        jLabel5.setToolTipText("");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        blue.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 20, 110, 110));

        jLabel6.setBackground(new java.awt.Color(65, 131, 215));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        blue.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 20, 110, 110));

        jLabel7.setBackground(new java.awt.Color(129, 207, 224));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        blue.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 20, 110, 110));

        jLabel9.setBackground(new java.awt.Color(89, 171, 227));
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        blue.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 20, 110, 110));

        jLabel10.setBackground(new java.awt.Color(52, 73, 94));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        blue.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 140, 110, 110));

        jLabel11.setBackground(new java.awt.Color(30, 139, 195));
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.setOpaque(true);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        blue.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 140, 110, 110));

        jLabel12.setBackground(new java.awt.Color(52, 152, 219));
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.setOpaque(true);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        blue.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 140, 110, 110));

        jLabel13.setBackground(new java.awt.Color(82, 179, 217));
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        blue.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 140, 110, 110));

        jLabel14.setBackground(new java.awt.Color(44, 62, 80));
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.setOpaque(true);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        blue.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 260, 110, 110));

        jLabel15.setBackground(new java.awt.Color(51, 110, 123));
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.setOpaque(true);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        blue.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 260, 110, 110));

        jLabel16.setBackground(new java.awt.Color(34, 49, 63));
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.setOpaque(true);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        blue.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 260, 110, 110));

        jLabel17.setBackground(new java.awt.Color(92, 151, 191));
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.setOpaque(true);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        blue.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 260, 110, 110));

        jLabel18.setBackground(new java.awt.Color(0, 153, 153));
        jLabel18.setFont(new java.awt.Font("Secret Code", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Back");
        jLabel18.setToolTipText("");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.setOpaque(true);
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        blue.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 80, 40));

        jLabel19.setBackground(new java.awt.Color(107, 185, 240));
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.setOpaque(true);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        blue.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 380, 110, 110));

        jLabel20.setBackground(new java.awt.Color(103, 128, 159));
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.setOpaque(true);
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        blue.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 380, 110, 110));

        jLabel21.setBackground(new java.awt.Color(107, 185, 240));
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.setOpaque(true);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        blue.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 380, 110, 110));

        getContentPane().add(blue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 480, 500));

        orange.setOpaque(false);
        orange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orangeMouseEntered(evt);
            }
        });
        orange.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Secret Code", 1, 48)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Copied");
        jPanel5.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 190, 80));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel5.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 120, -1));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel5.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 120, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel5.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 120, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel5.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 120, -1));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/LABEL.png"))); // NOI18N
        jPanel5.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 120, -1));

        orange.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 480, 110));

        jLabel55.setBackground(new java.awt.Color(253, 227, 167));
        jLabel55.setToolTipText("");
        jLabel55.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel55.setOpaque(true);
        jLabel55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel55MouseClicked(evt);
            }
        });
        orange.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 20, 110, 110));

        jLabel56.setBackground(new java.awt.Color(248, 148, 6));
        jLabel56.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel56.setOpaque(true);
        jLabel56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel56MouseClicked(evt);
            }
        });
        orange.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 20, 110, 110));

        jLabel57.setBackground(new java.awt.Color(232, 126, 4));
        jLabel57.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel57.setOpaque(true);
        jLabel57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel57MouseClicked(evt);
            }
        });
        orange.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 20, 110, 110));

        jLabel58.setBackground(new java.awt.Color(235, 149, 50));
        jLabel58.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel58.setOpaque(true);
        jLabel58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel58MouseClicked(evt);
            }
        });
        orange.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 20, 110, 110));

        jLabel59.setBackground(new java.awt.Color(245, 171, 53));
        jLabel59.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel59.setOpaque(true);
        jLabel59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel59MouseClicked(evt);
            }
        });
        orange.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 140, 110, 110));

        jLabel60.setBackground(new java.awt.Color(235, 151, 78));
        jLabel60.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel60.setOpaque(true);
        jLabel60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel60MouseClicked(evt);
            }
        });
        orange.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 140, 110, 110));

        jLabel61.setBackground(new java.awt.Color(242, 120, 75));
        jLabel61.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel61.setOpaque(true);
        jLabel61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel61MouseClicked(evt);
            }
        });
        orange.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 140, 110, 110));

        jLabel62.setBackground(new java.awt.Color(244, 179, 80));
        jLabel62.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel62.setOpaque(true);
        jLabel62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel62MouseClicked(evt);
            }
        });
        orange.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 140, 110, 110));

        jLabel63.setBackground(new java.awt.Color(230, 126, 34));
        jLabel63.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel63.setOpaque(true);
        jLabel63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel63MouseClicked(evt);
            }
        });
        orange.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 260, 110, 110));

        jLabel64.setBackground(new java.awt.Color(242, 121, 53));
        jLabel64.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel64.setOpaque(true);
        jLabel64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel64MouseClicked(evt);
            }
        });
        orange.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 260, 110, 110));

        jLabel65.setBackground(new java.awt.Color(243, 156, 18));
        jLabel65.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel65.setOpaque(true);
        jLabel65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel65MouseClicked(evt);
            }
        });
        orange.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 260, 110, 110));

        jLabel66.setBackground(new java.awt.Color(211, 84, 0));
        jLabel66.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel66.setOpaque(true);
        jLabel66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel66MouseClicked(evt);
            }
        });
        orange.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 260, 110, 110));

        jLabel67.setBackground(new java.awt.Color(0, 153, 153));
        jLabel67.setFont(new java.awt.Font("Secret Code", 1, 24)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("Back");
        jLabel67.setToolTipText("");
        jLabel67.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel67.setOpaque(true);
        jLabel67.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel67MouseClicked(evt);
            }
        });
        orange.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 80, 40));

        jLabel68.setBackground(new java.awt.Color(255, 162, 0));
        jLabel68.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel68.setOpaque(true);
        jLabel68.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel68MouseClicked(evt);
            }
        });
        orange.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 380, 110, 110));

        jLabel69.setBackground(new java.awt.Color(249, 191, 59));
        jLabel69.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel69.setOpaque(true);
        jLabel69.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel69MouseClicked(evt);
            }
        });
        orange.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 380, 110, 110));

        jLabel70.setBackground(new java.awt.Color(249, 105, 14));
        jLabel70.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel70.setOpaque(true);
        jLabel70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel70MouseClicked(evt);
            }
        });
        orange.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 380, 110, 110));

        getContentPane().add(orange, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 480, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flatcolorpicker/b.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked
    int x,y;
    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseDragged
        this.setLocation(evt.getXOnScreen()-x,evt.getYOnScreen()-y);
    }//GEN-LAST:event_jLabel4MouseDragged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocation((int)((Toolkit.getDefaultToolkit().getScreenSize().width/2)-250),50);
        blue.setVisible(false);
        red.setVisible(false);
        purple.setVisible(false);
        yellow.setVisible(false);
        orange.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        main.setVisible(true);
        blue.setVisible(false);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        color("228,241,254","#E4F1FE");
    }//GEN-LAST:event_jLabel5MouseClicked
public static boolean hexrgb = false ;
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if(hexrgb == false ) {
            hexrgb = true;
            jLabel8.setIcon(new ImageIcon(getClass().getResource("hex.png")));
        }
        else {
            hexrgb = false;
            jLabel8.setIcon(new ImageIcon(getClass().getResource("rbg.png")));
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void c1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseClicked
        main.setVisible(false);
        blue.setVisible(true);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_c1MouseClicked
public void color(String r,String h){
    
    Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard ();        
    if(hexrgb == false) clpbrd.setContents (new StringSelection (r), null);
    else clpbrd.setContents (new StringSelection (h), null);
    
    if(blue.isVisible())    jPanel1.setVisible(true);
    if(red.isVisible()) jPanel2.setVisible(true);     
    if(purple.isVisible())  jPanel3.setVisible(true); 
    if(yellow.isVisible())  jPanel4.setVisible(true); 
    if(orange.isVisible())  jPanel5.setVisible(true);
    
}

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        color(hex2Rgb(gethex(jLabel6)),gethex(jLabel6));
    }//GEN-LAST:event_jLabel6MouseClicked

    private void blueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blueMouseEntered
        jPanel1.setVisible(false);   
    }//GEN-LAST:event_blueMouseEntered

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        color(hex2Rgb(gethex(jLabel9)),gethex(jLabel9));
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        color(hex2Rgb(gethex(jLabel7)),gethex(jLabel7));
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        color(hex2Rgb(gethex(jLabel13)),gethex(jLabel13));
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        color(hex2Rgb(gethex(jLabel12)),gethex(jLabel12));
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        color(hex2Rgb(gethex(jLabel11)),gethex(jLabel11));
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        color(hex2Rgb(gethex(jLabel10)),gethex(jLabel10));
    }//GEN-LAST:event_jLabel10MouseClicked

    public String gethex(javax.swing.JLabel g){
        return ("#" + String.format("%06x", g.getBackground().getRGB() & (0x00FFFFFF)));
    }
    public static String hex2Rgb(String colorStr) {
        return (Integer.valueOf( colorStr.substring( 1, 3 ), 16 )+ ","+Integer.valueOf( colorStr.substring( 3, 5 ), 16 )+ ","+Integer.valueOf( colorStr.substring( 5, 7 ), 16 ) + "") ;
    }
    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        color(hex2Rgb(gethex(jLabel17)),gethex(jLabel17));
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        color(hex2Rgb(gethex(jLabel16)),gethex(jLabel16));
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        color(hex2Rgb(gethex(jLabel15)),gethex(jLabel15));
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        color(hex2Rgb(gethex(jLabel14)),gethex(jLabel14));
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        color(hex2Rgb(gethex(jLabel21)),gethex(jLabel21));
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
         color(hex2Rgb(gethex(jLabel20)),gethex(jLabel20));
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
         color(hex2Rgb(gethex(jLabel19)),gethex(jLabel19));
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel46MouseClicked
        red.setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_jLabel46MouseClicked

    private void redMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redMouseEntered
        jPanel2.setVisible(false);
    }//GEN-LAST:event_redMouseEntered

    private void c19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c19MouseClicked
        color(hex2Rgb(gethex(c19)),gethex(c19));
    }//GEN-LAST:event_c19MouseClicked

    private void c2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MouseClicked
        main.setVisible(false);
        red.setVisible(true);
        jPanel2.setVisible(false);
    }//GEN-LAST:event_c2MouseClicked

    private void c18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c18MouseClicked
        color(hex2Rgb(gethex(c18)),gethex(c18));
    }//GEN-LAST:event_c18MouseClicked

    private void c17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c17MouseClicked
        color(hex2Rgb(gethex(c17)),gethex(c17));
    }//GEN-LAST:event_c17MouseClicked

    private void c14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c14MouseClicked
        color(hex2Rgb(gethex(c14)),gethex(c14));
    }//GEN-LAST:event_c14MouseClicked

    private void c15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c15MouseClicked
        color(hex2Rgb(gethex(c15)),gethex(c15));
    }//GEN-LAST:event_c15MouseClicked

    private void c16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c16MouseClicked
        color(hex2Rgb(gethex(c16)),gethex(c16));
    }//GEN-LAST:event_c16MouseClicked

    private void c13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c13MouseClicked
        color(hex2Rgb(gethex(c13)),gethex(c13));
    }//GEN-LAST:event_c13MouseClicked

    private void c20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c20MouseClicked
        color(hex2Rgb(gethex(c20)),gethex(c20));
    }//GEN-LAST:event_c20MouseClicked

    private void c12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c12MouseClicked
        color(hex2Rgb(gethex(c12)),gethex(c12));
    }//GEN-LAST:event_c12MouseClicked

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        purple.setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_jLabel47MouseClicked

    private void c21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c21MouseClicked
        color(hex2Rgb(gethex(c21)),gethex(c21));
    }//GEN-LAST:event_c21MouseClicked

    private void c22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c22MouseClicked
        color(hex2Rgb(gethex(c22)),gethex(c22));
    }//GEN-LAST:event_c22MouseClicked

    private void c23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c23MouseClicked
        color(hex2Rgb(gethex(c23)),gethex(c23));
    }//GEN-LAST:event_c23MouseClicked

    private void c24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c24MouseClicked
        color(hex2Rgb(gethex(c24)),gethex(c24));
    }//GEN-LAST:event_c24MouseClicked

    private void c25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c25MouseClicked
        color(hex2Rgb(gethex(c25)),gethex(c25));
    }//GEN-LAST:event_c25MouseClicked

    private void c26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c26MouseClicked
        color(hex2Rgb(gethex(c26)),gethex(c26));
    }//GEN-LAST:event_c26MouseClicked

    private void c27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c27MouseClicked
        color(hex2Rgb(gethex(c27)),gethex(c27));
    }//GEN-LAST:event_c27MouseClicked

    private void c28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c28MouseClicked
        color(hex2Rgb(gethex(c28)),gethex(c28));
    }//GEN-LAST:event_c28MouseClicked

    private void c29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c29MouseClicked
        color(hex2Rgb(gethex(c29)),gethex(c29));
    }//GEN-LAST:event_c29MouseClicked

    private void purpleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purpleMouseEntered
        jPanel3.setVisible(false);
    }//GEN-LAST:event_purpleMouseEntered

    private void c3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3MouseClicked
        purple.setVisible(true);
        main.setVisible(false);
        jPanel3.setVisible(false);
    }//GEN-LAST:event_c3MouseClicked

    private void jLabel48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel48MouseClicked
        yellow.setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_jLabel48MouseClicked

    private void c32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c32MouseClicked
        color(hex2Rgb(gethex(c32)),gethex(c32));
    }//GEN-LAST:event_c32MouseClicked

    private void c33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c33MouseClicked
        color(hex2Rgb(gethex(c33)),gethex(c33));
    }//GEN-LAST:event_c33MouseClicked

    private void c34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c34MouseClicked
        color(hex2Rgb(gethex(c34)),gethex(c34));
    }//GEN-LAST:event_c34MouseClicked

    private void c36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c36MouseClicked
        color(hex2Rgb(gethex(c36)),gethex(c36));
    }//GEN-LAST:event_c36MouseClicked

    private void c38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c38MouseClicked
        color(hex2Rgb(gethex(c38)),gethex(c38));
    }//GEN-LAST:event_c38MouseClicked

    private void yellowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yellowMouseEntered
        jPanel4.setVisible(false);
    }//GEN-LAST:event_yellowMouseEntered

    private void c4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c4MouseClicked
        main.setVisible(false);
        yellow.setVisible(true);
        jPanel4.setVisible(false);
    }//GEN-LAST:event_c4MouseClicked

    private void jLabel55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel55MouseClicked
        color(hex2Rgb(gethex( jLabel55)),gethex(jLabel55));
    }//GEN-LAST:event_jLabel55MouseClicked

    private void jLabel56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel56MouseClicked
        color(hex2Rgb(gethex( jLabel56)),gethex(jLabel56));
    }//GEN-LAST:event_jLabel56MouseClicked

    private void jLabel57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel57MouseClicked
        color(hex2Rgb(gethex( jLabel57)),gethex(jLabel57));
    }//GEN-LAST:event_jLabel57MouseClicked

    private void jLabel58MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel58MouseClicked
        color(hex2Rgb(gethex( jLabel58)),gethex(jLabel58));
    }//GEN-LAST:event_jLabel58MouseClicked

    private void jLabel59MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel59MouseClicked
        color(hex2Rgb(gethex( jLabel59)),gethex(jLabel59));
    }//GEN-LAST:event_jLabel59MouseClicked

    private void jLabel60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseClicked
        color(hex2Rgb(gethex( jLabel59)),gethex(jLabel59));
    }//GEN-LAST:event_jLabel60MouseClicked

    private void jLabel61MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel61MouseClicked
        color(hex2Rgb(gethex( jLabel61)),gethex(jLabel61));
    }//GEN-LAST:event_jLabel61MouseClicked

    private void jLabel62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel62MouseClicked
        color(hex2Rgb(gethex( jLabel62)),gethex(jLabel62));
    }//GEN-LAST:event_jLabel62MouseClicked

    private void jLabel63MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel63MouseClicked
       color(hex2Rgb(gethex( jLabel63)),gethex(jLabel63));
    }//GEN-LAST:event_jLabel63MouseClicked

    private void jLabel64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel64MouseClicked
        color(hex2Rgb(gethex( jLabel64)),gethex(jLabel64));
    }//GEN-LAST:event_jLabel64MouseClicked

    private void jLabel65MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel65MouseClicked
        color(hex2Rgb(gethex( jLabel65)),gethex(jLabel65));
    }//GEN-LAST:event_jLabel65MouseClicked

    private void jLabel66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel66MouseClicked
        color(hex2Rgb(gethex( jLabel66)),gethex(jLabel66));
    }//GEN-LAST:event_jLabel66MouseClicked

    private void jLabel67MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel67MouseClicked
        orange.setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_jLabel67MouseClicked

    private void jLabel68MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel68MouseClicked
        color(hex2Rgb(gethex( jLabel68)),gethex(jLabel68));
    }//GEN-LAST:event_jLabel68MouseClicked

    private void jLabel69MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel69MouseClicked
        color(hex2Rgb(gethex( jLabel69)),gethex(jLabel69));
    }//GEN-LAST:event_jLabel69MouseClicked

    private void jLabel70MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel70MouseClicked
        color(hex2Rgb(gethex( jLabel70)),gethex(jLabel70));
    }//GEN-LAST:event_jLabel70MouseClicked

    private void orangeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orangeMouseEntered
        jPanel5.setVisible(false);
    }//GEN-LAST:event_orangeMouseEntered

    private void c5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c5MouseClicked
        main.setVisible(false);
        orange.setVisible(true);
        jPanel5.setVisible(false);
    }//GEN-LAST:event_c5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maibn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maibn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maibn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maibn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maibn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blue;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c10;
    private javax.swing.JLabel c12;
    private javax.swing.JLabel c13;
    private javax.swing.JLabel c14;
    private javax.swing.JLabel c15;
    private javax.swing.JLabel c16;
    private javax.swing.JLabel c17;
    private javax.swing.JLabel c18;
    private javax.swing.JLabel c19;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c20;
    private javax.swing.JLabel c21;
    private javax.swing.JLabel c22;
    private javax.swing.JLabel c23;
    private javax.swing.JLabel c24;
    private javax.swing.JLabel c25;
    private javax.swing.JLabel c26;
    private javax.swing.JLabel c27;
    private javax.swing.JLabel c28;
    private javax.swing.JLabel c29;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c32;
    private javax.swing.JLabel c33;
    private javax.swing.JLabel c34;
    private javax.swing.JLabel c36;
    private javax.swing.JLabel c38;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c7;
    private javax.swing.JLabel c8;
    private javax.swing.JLabel c9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel main;
    private javax.swing.JPanel orange;
    private javax.swing.JPanel purple;
    private javax.swing.JPanel red;
    private javax.swing.JPanel yellow;
    // End of variables declaration//GEN-END:variables

}
